### ISSUE TITLE
Lookerbot fails to show looks with visualizations

### ISSUE THREAD

**Issue by nijine** [looker/lookerbot#151]
It appears that this isn't a new issue, but I haven't found a solution in any of the related issues previous posted. 

When we ask lookerbot to return a look with a visualization, we always get "An error has occurred" in return, no matter how it is called. If we request a look that just returns a number, that works fine.

Our lookerbot instance is hosted as a service in AWS ECS, and all of the relevant AWS / S3 environment variables are set, but it appears the issue happens long before these are required.

Poking around our server logs, this is what we found around the time the error is returned. This is with "Enhanced Rendering" turned on:
`StandardError : Render job f00f815792ae48c169f8da2b250979e1[78] failed [renderer no outfile - retried]`

We tried turning off "Enhanced Rendering" to see if it had any effect, and we get the same error message in slack, but the logs show something different:`StandardError : Render job 25889c0bd821ed92ecb42e8dae822c20[81] failed ["Unexpected document content"]`

Our looker version is 6.0.20. Please let me know if I missed anything.

**Comment by lucasoptimizely** [comment]
hi @iamthemouth , is there any update on this issue? We flagged this problem months ago when we implemented Lookerbot and it continues to be a problem for us.

**Comment by iamthemouth** [comment]
Hi @lucasoptimizely , Apologies for the radio silence on this and thank you for bringing it back up to the forefront. We've pushed several changes to Looker since this ticket opened that should have greatly reduced the number of render errors but it sounds like unfortunately you're still experiencing this behavior so there's more work to be done. 

So that I can create a reproduction case for testing would you mind confirming your current version of Looker and whether you have either the enhanced or legacy renderer enabled?

**Comment by natarajanc** [comment]
@iamthemouth we are on looker 6.6.14 and are also using the latest master branch of the looker/lookerbot - we also dont see any labs feature for enhanced rendering

**Comment by iamthemouth** [comment]
Hi @natarajanc thanks for the response. This issue definitely shouldn't still be occurring in versions 6.6 and greater but it looks like there's an outstanding issue that we thought we had resolved but haven't yet. Enhanced (Chromium) rendering is out of labs in 6.6 so that explains why you're not seeing the feature, instead you should have a legacy feature to enable the old (phantom) renderer should you choose. I'd like to work with you on creating a reproduction case and maybe examine some logs from your instance. In the interest of data safety and privacy that should probably happen in a more private format. Would you mind reaching out via email (wyatt.mcguire@looker.com) so that we can gather a bit more information?

**Comment by Isaac-Rahman** [comment]
Sorry to hijack this thread but we're having the exact same issue. Looks with tables work fine but anything with a viz (bar charts, line graphs etc.) all fail. Within our logs we can see a call being made to Looker for the PNG of the viz but it gets stuck there and times out after 50 minutes when it displays an error.

We're on version 6.6.19. Is this something you can also help with @iamthemouth? If not, could you maybe direct me to the right person for support?

Thank you

**Comment by iamthemouth** [comment]
Hi @Isaac-Rahman I'm sorry to hear that you're experiencing this trouble, however I thank you for adding your comment as it is very valuable information to have as knowing that this issue is affecting more than one instance helps us to track down the cause of the problem so we can find a solution. The rest of the team and I are working diligently to resolve this as soon as possible for you and will provide updates as new information or a fix becomes available. Would you mind reaching out via email (wyatt.mcguire@looker.com) so that I can ask you a few questions for diagnostic purposes that are probably best kept off of a public forum? Thanks again for reaching out.

**Comment by chrismaher** [comment]
Hi @iamthemouth, I work with @nijine, and this same issue persists for us with version 6.10.14 (i.e. Lookerbot works with single-number dashboards, but fails to write any visualizations to S3). Can you share what you've done with other users to resolve it?
